version: "2"
networks:
  back-tier:
    driver: bridge
services:
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    links:
      - mongo
      - redis 
    networks:
      - back-tier
  mongo:
    container_name: mongo
    build: ./mongo
    ports:
      - "27017:27017"
    networks:
      - back-tier    
  redis:
    container_name: redis
    build: ./redis
    ports:
      - "6379:6379"
    networks:
      - back-tier
  mongodata:
    build: ./mongodata
    links:
      - mongo  
    networks:
      - back-tier   
       
